camunda.bpm.admin-user:
  id: demo
  password: demopass

camunda.bpm.deployment-resource-pattern: processes/*.bpmn

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

camunda:
  bpm:
    deployment-resource-pattern: classpath:/processes/*.bpmn
    process-engine-name: default
    database:
      type: h2
    history-level: full # Ensure history level is set to capture data
    generic-properties:
      properties:
        historyTimeToLive: P1D


